// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function factorial(n) {
  if (n <= 0) {
    return 1;
  } else {
    return Caml_int32.imul(n, factorial(n - 1 | 0));
  }
}

console.log(factorial(10));

function fizzbuzz(i) {
  var match = i % 3;
  var match$1 = i % 5;
  if (match !== 0) {
    if (match$1 !== 0) {
      return i.toString();
    } else {
      return "Buzz";
    }
  } else if (match$1 !== 0) {
    return "Fizz";
  } else {
    return "FizzBuzz";
  }
}

for(var i = 1; i <= 100; ++i){
  console.log(fizzbuzz(i));
}

var hasan = {
  name: "Hasan",
  age: 24
};

function display(param) {
  console.log(" " + (String(param.name) + (" is " + (String(param.age) + " years old."))));
  return /* () */0;
}

function getIntType(num) {
  if (num >= 0) {
    if (num === 1) {
      return /* One */0;
    } else {
      return /* Pos */3;
    }
  } else if (num === -1) {
    return /* NegOne */1;
  } else {
    return /* Neg */2;
  }
}

function display_another(param) {
  var age = param.age;
  var name = param.name;
  var match = getIntType(age);
  switch (match) {
    case /* One */0 :
        console.log(" " + (String(name) + " is a year old."));
        return /* () */0;
    case /* NegOne */1 :
        console.log(" " + (String(name) + " will be born in a year."));
        return /* () */0;
    case /* Neg */2 :
        console.log(name + (" will be born in " + (Caml_int32.imul(age, -1).toString() + " years.")));
        return /* () */0;
    case /* Pos */3 :
        console.log(" " + (String(name) + (" is " + (String(age) + " years old."))));
        return /* () */0;
    
  }
}

function display_clean(param) {
  var age = param.age;
  var name = param.name;
  if (age >= 0) {
    if (age === 1) {
      console.log(" " + (String(name) + " is a year old."));
      return /* () */0;
    } else {
      console.log(" " + (String(name) + (" is " + (String(age) + " years old."))));
      return /* () */0;
    }
  } else if (age === -1) {
    console.log(" " + (String(name) + " will be born in a year."));
    return /* () */0;
  } else {
    console.log(name + (" will be born in " + (Caml_int32.imul(age, -1).toString() + " years.")));
    return /* () */0;
  }
}

display_clean(hasan);

console.log("");

console.log("Display 1:");

for(var i$1 = -10; i$1 <= 10; ++i$1){
  display({
        name: "Hasan",
        age: i$1
      });
}

console.log("Display 2:");

for(var i$2 = -10; i$2 <= 10; ++i$2){
  display_another({
        name: "Hasan",
        age: i$2
      });
}

console.log("Display 3:");

for(var i$3 = -10; i$3 <= 10; ++i$3){
  display_clean({
        name: "Hasan",
        age: i$3
      });
}

exports.factorial = factorial;
exports.fizzbuzz = fizzbuzz;
exports.hasan = hasan;
exports.display = display;
exports.getIntType = getIntType;
exports.display_another = display_another;
exports.display_clean = display_clean;
/*  Not a pure module */
